---
title: "Ozone Paper Plots"
author: "Fatemeh Kazemi"
date: "6-15-2022"
---

### plots subgroups using different colors and shapes
###color codes: https://www.schemecolor.com/british-airways-website.php

```{r}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r Load packages}
library(tidyverse)
library(here)
library(ggthemes)
```

```{r Call Functions}
#source(here('code','data-viz','forest-plot-functions.R'))
```

```{r Load data}
load(here('output','analysis','out-main.RDa'))
# load(here('output','analysis','out-age.RDa'))
# load(here('output','analysis','out-sex.RDa'))
# load(here('output','analysis','out-race.RDa'))
load(here('output','analysis','out-asr.RDa'))
# load(here('output','analysis','out-urbanicity.RDa'))
# load(here('output','analysis','out-sesUrban.RDa'))
load(here('output','analysis','out-region.RDa'))
load(here('output','analysis','out-buffer.RDa'))
load(here('output','analysis','out-exposure.RDa'))
load(here('output','analysis','out-brfss.RDa'))
```

<br>

```{r}
ggtheme.single <- theme_bw() + 
  theme(panel.spacing.y = unit(c(0,0.25, 0, 0, 0, 0.25, 0, 0, 0.25, 0, 0.25, 0.25, 0, 0, 0.25, 0, 0, 0.25),'lines'),
        panel.spacing.x = unit(0.25,'lines'),
        panel.border = element_rect(fill = NA, 'lines', color = "gray25"),
        strip.text.x = element_text(size = 14, color = 'black', 
                                    face = 'bold'),
        strip.text.y.left = element_text(size = 14, color = 'black', 
                                         face = 'bold', angle = 0, hjust = 0),
        strip.background = element_rect(fill = "#B9CFED"),
        axis.text.x = element_text(size = 12, color = 'black'),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size = 14, color = 'black', 
                                   face = 'bold'),
        legend.position = 'bottom')
```

```{r set theme 1}
ggtheme.single <- theme_bw() + 
  theme(axis.text.x = element_text(size = 14, color = 'black'),
        axis.text.y =  element_text(size = 14, face = 'bold', color = 'black'),
        axis.ticks.y = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size = 14, color = 'black', 
                                   face = 'bold')
  )
```

<br>

```{r set theme 2}
ggtheme.multi <- theme_bw() + 
  theme(panel.spacing.x = unit(0.25,'lines'),
        panel.border = element_rect(fill = NA, 'lines', color = "gray25"),
        strip.text.x = element_text(size = 16, color = 'black', 
                                    face = 'bold'),
        strip.text.y.left = element_text(size = 16, color = 'black', 
                                         face = 'bold', angle = 0, hjust = 0),
        strip.background = element_rect(fill = "#B9CFED"),
        axis.text.x = element_text(size = 14, color = 'black'),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size = 16, color = 'black', 
                                   face = 'bold'),
        legend.position = "bottom"
  )
```

```{r}
cuz <- c("All-Cause", "Cardiovascular", "IHD", "CHF", "CBV", 
         "Respiratory", "COPD", "Pneumonia", "Cancer", "Lung Cancer", 
         "Sepsis", "Type1 Diabetes", "Type2 Diabetes")
```

<br>

# Ghraphical Abs
```{r - xxx, fig.dim = c(7.5, 6.5)}

```

<br>
### All models
```{r - All models, fig.dim = c(7.5, 6.5)}
data <- out.main %>% 
  filter(Cause %in% cuz)

plot.cols <- c("#EB2226")

Plot.Single(dt = data, ggtheme = ggtheme.single) +
ggsave(here('output','plot','out-main-all.jpeg'), width = 7.5, height = 6.5, dpi = 600)
```

<br>

### State + SES + PM Adjusted
```{r - main model, fig.dim = c(7.5, 6.5)}
data <- out.main %>% 
  filter(Cause %in% cuz,
         Value == "+ State + SES + PM2.5")

plot.cols <- c("#EB2226")

Plot.Single(dt = data, ggtheme = ggtheme.single) +
ggsave(here('output','plot','pmc-ses.jpeg'), width = 7.5, height = 6.5, dpi = 600)
```


```{r}
panel.spacing.y = unit(c(0.25, 0, 0, 0, 0.25, 0, 0, 0.25, 0, 0.25, 0.25, 0),'lines'),
```

