---
title: "Analysis Output files"
---

https://cran.r-project.org/web/packages/forestplot/vignettes/forestplot.html
https://cran.r-project.org/web/packages/metaviz/vignettes/metaviz.html

```{r}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r load packages}
library(tidyverse)
library(here)
```

```{r Load data}
```

```{r Outcome to Cause }
Outcome.to.Cause <- tribble(
  ~Cause, ~Outcome,
  "All-Cause", "allcuz",
  "Non-Accidental", "nacc",
  "Accidental", "acc",
  "Cardiovascular", "cvd",
  "IHD", "ihd",
  "CHF", "chf",
  "CBV", "cbv",
  "Respiratory", "resp",
  "COPD", "copd",
  "Pneumonia", "pneu",
  "URI", "uri",
  "ARDS", "ards",
  "Cancer", "canc",
  "Lung Cancer", "lungc",
  "Sepsis", "seps",
  "Vascular dementia", "VaD",
  "Alzheimer", "AD",
  "Neurodegeneration", "NeD",
  "Unspecified Dementia", "UsD",
  "Type1 Diabetes", "diabt1",
  "Type2 Diabetes", "diabt2",
  "Diabetes", "diab",
  "Kidney Disease", "kidn"
)

cuz <- c("All-Cause", "Non-Accidental", "Accidental", "Cardiovascular",
         "IHD", "CHF", "CBV", "Respiratory", "COPD", "Pneumonia", "URI",
         "ARDS", "Cancer", "Lung Cancer", "Sepsis", "Vascular dementia",
         "Alzheimer", "Neurodegeneration", "Unspecified Dementia", 
         "Type1 Diabetes", "Type2 Diabetes", "Diabetes", "Kidney Disease")
```

```{r Output Base}
out.base.t = data.frame()
for (i in 1:4){
  load(here('output','analysis', 'New folder', paste('out-base-',i,'.RDa', sep= "")))
  out.base.t  <-  rbind(out.base.t, out.base) %>% drop_na()
  }

out.base <- out.base.t %>% 
  merge(Outcome.to.Cause) %>% 
  mutate(Coef = as.numeric(as.character(O3_B)),
         std = as.numeric(as.character(O3_SE)),
         HR = round(exp(Coef * 10/1000),3),
         HR.L = round(exp((Coef-1.96*std) * 10/1000),3),
         HR.U = round(exp((Coef+1.96*std) * 10/1000),3),
         Subgroup = "Total", 
         Value = "Base") %>% 
  select(Cause, Subgroup, Value, HR, HR.L, HR.U)

rm(out.base.t)
```

```{r Output State}
out.state.t = data.frame()
for (i in 1:4){
  load(here('output','analysis', 'New folder', paste('out-state-',i,'.RDa', sep= "")))
  out.state.t  <-  rbind(out.state.t, out.state) %>% drop_na()
  }

out.state <- out.state.t %>% 
  merge(Outcome.to.Cause) %>% 
  mutate(Coef = as.numeric(as.character(O3_B)),
         std = as.numeric(as.character(O3_SE)),
         HR = round(exp(Coef * 10/1000),3),
         HR.L = round(exp((Coef-1.96*std) * 10/1000),3),
         HR.U = round(exp((Coef+1.96*std) * 10/1000),3),
         Subgroup = "Total", 
         Value = "+ State") %>% 
  select(Cause, Subgroup, Value, HR, HR.L, HR.U)

rm(out.state.t)
```

```{r Output SES}
out.ses.t = data.frame()
for (i in 1:4){
  load(here('output','analysis','New folder', paste('out-ses-',i,'.RDa', sep= "")))
  out.ses.t  <-  rbind(out.ses.t, out.ses) %>% drop_na()
  }

out.ses <- out.ses.t %>% 
  merge(Outcome.to.Cause) %>% 
  mutate(Coef = as.numeric(as.character(O3_B)),
         std = as.numeric(as.character(O3_SE)),
         HR = round(exp(Coef * 10/1000),3),
         HR.L = round(exp((Coef-1.96*std) * 10/1000),3),
         HR.U = round(exp((Coef+1.96*std) * 10/1000),3),
         Subgroup = "Total", 
         Value = "+ State + SES") %>% 
  select(Cause, Subgroup, Value, HR, HR.L, HR.U)

rm(out.ses.t)
```

```{r Output PM}
out.pm25.t = data.frame()
for (i in 1:4){
  load(here('output','analysis', 'New folder', paste('out-pm-',i,'.RDa', sep= "")))
  out.pm25.t  <-  rbind(out.pm25.t, out.pm) %>% drop_na()
  }

out.pm25 <- out.pm25.t %>% 
  merge(Outcome.to.Cause) %>% 
  mutate(Coef = as.numeric(as.character(O3_B)),
         std = as.numeric(as.character(O3_SE)),
         HR = round(exp(Coef * 10/1000),3),
         HR.L = round(exp((Coef-1.96*std) * 10/1000),3),
         HR.U = round(exp((Coef+1.96*std) * 10/1000),3),
         Subgroup = "Total", 
         Value = "+ State + SES + PM2.5") %>% 
  select(Cause, Subgroup, Value, HR, HR.L, HR.U)

rm(out.pm25.t, out.pm)
```

```{r Output NO2}
out.no2.t = data.frame()
for (i in 1:4){
  load(here('output','analysis','New folder', paste('out-no2-',i,'.RDa', sep= "")))
  out.no2.t  <-  rbind(out.no2.t, out.no2) %>% drop_na()
  }

out.no2 <- out.no2.t %>% 
  merge(Outcome.to.Cause) %>% 
  mutate(Coef = as.numeric(as.character(O3_B)),
         std = as.numeric(as.character(O3_SE)),
         HR = round(exp(Coef * 10/1000),3),
         HR.L = round(exp((Coef-1.96*std) * 10/1000),3),
         HR.U = round(exp((Coef+1.96*std) * 10/1000),3),
         Subgroup = "Total", 
         Value = "+ State + SES + NO2") %>% 
  select(Cause, Subgroup, Value, HR, HR.L, HR.U)

rm(out.no2.t)
```

```{r}
out.main <- out.base %>% 
  add_row(out.state) %>% 
  add_row(out.ses) %>% 
  add_row(out.pm25) %>% 
  add_row(out.no2) %>% 
  mutate(Value = factor(Value, levels = c("+ State + SES + NO2",
                                          "+ State + SES + PM2.5",
                                          "+ State + SES", "+ State","Base")),
         Cause = factor(Cause, levels = cuz))

save(out.main, file = here('output','analysis','out-main.RDa'))
```

```{r Output Age}
out.le.t = data.frame()
for (i in 1:4){
  load(here('output','analysis', 'New folder', paste('out-le-',i,'.RDa', sep= "")))
  out.le.t  <-  rbind(out.le.t, age.le) %>% drop_na()
  }

out.mt.t = data.frame()
for (i in 1:4){
  load(here('output','analysis', 'New folder', paste('out-mt-',i,'.RDa', sep= "")))
  out.mt.t  <-  rbind(out.mt.t, age.mt) %>% drop_na()
  }

out.age.t <- out.le.t %>% 
  add_row(out.mt.t)
  
out.age <- out.age.t %>% 
  merge(Outcome.to.Cause) %>% 
  mutate(Coef = as.numeric(as.character(O3_B)),
         std = as.numeric(as.character(O3_SE)),
         HR = round(exp(Coef * 10/1000),3),
         HR.L = round(exp((Coef-1.96*std) * 10/1000),3),
         HR.U = round(exp((Coef+1.96*std) * 10/1000),3),
         Subgroup = "Age", 
         Value = case_when(Age_Cat == "LE75" ~ "65-75",
                           T ~ ">75"),
         Value = factor(Value, levels = c(">75", "65-75")),
         Cause = factor(Cause, levels = cuz)) %>% 
  select(Cause, Subgroup, Value, HR, HR.L, HR.U, pValue)

save(out.age, file = here('output','analysis','out-age.RDa'))

rm(out.le.t, out.mt.t, out.age.t, age.le, age.mt)
```

```{r Output Sex}
out.f.t = data.frame()
for (i in 1:4){
  load(here('output','analysis', 'New folder', paste('out-sexF-',i,'.RDa', sep= "")))
  out.f.t  <-  rbind(out.f.t, sex.F) %>% drop_na()
  }

out.m.t = data.frame()
for (i in 1:4){
  load(here('output','analysis', 'New folder', paste('out-sexM-',i,'.RDa', sep= "")))
  out.m.t  <-  rbind(out.m.t, sex.M) %>% drop_na()
  }

out.sex.t <- out.f.t %>% 
  add_row(out.m.t)
  
out.sex <- out.sex.t %>% 
  merge(Outcome.to.Cause) %>% 
  mutate(Coef = as.numeric(as.character(O3_B)),
         std = as.numeric(as.character(O3_SE)),
         HR = round(exp(Coef * 10/1000),3),
         HR.L = round(exp((Coef-1.96*std) * 10/1000),3),
         HR.U = round(exp((Coef+1.96*std) * 10/1000),3),
         Subgroup = "Sex", 
         Value = case_when(sex_Cat == "F" ~ "Female",
                           T ~ "Male"),
         Value = factor(Value, levels = c("Male", "Female")),
         Cause = factor(Cause, levels = cuz)) %>% 
  select(Cause, Subgroup, Value, HR, HR.L, HR.U, pValue)

save(out.sex, file = here('output','analysis','out-sex.RDa'))

rm(out.f.t, out.m.t, out.sex.t, sex.F, sex.M)
```

```{r Output Urbanicity}
out.urban.t = data.frame()
for (i in 1:4){
  load(here('output','analysis', 'New folder', paste('out-urban-',i,'.RDa', sep= "")))
  out.urban.t  <-  rbind(out.urban.t, loc.urban) %>% 
    filter(!is.na(Outcome))
  }

out.suburban.t = data.frame()
for (i in 1:4){
  load(here('output','analysis', 'New folder', paste('out-suburban-',i,'.RDa', sep= "")))
  out.suburban.t  <-  rbind(out.suburban.t, loc.suburban) %>% 
    filter(!is.na(Outcome))
  }

out.rural.t = data.frame()
for (i in 1:4){
  load(here('output','analysis', 'New folder', paste('out-rural-',i,'.RDa', sep= "")))
  out.rural.t  <-  rbind(out.rural.t, loc.rural) %>% 
    filter(!is.na(Outcome))
  }

out.urbanicity.t <- out.urban.t %>% 
  add_row(out.suburban.t) %>% 
  add_row(out.rural.t)
  
out.urbanicity <- out.urbanicity.t %>% 
  merge(Outcome.to.Cause) %>% 
  mutate(Coef = as.numeric(as.character(O3_B)),
         std = as.numeric(as.character(O3_SE)),
         HR = round(exp(Coef * 10/1000),3),
         HR.L = round(exp((Coef-1.96*std) * 10/1000),3),
         HR.U = round(exp((Coef+1.96*std) * 10/1000),3),
         Subgroup = "Urbanicity", 
         Value = str_to_title(Loc_Set),
         Value = factor(Value, levels = c("Rural", "Suburban", "Urban")),
         Cause = factor(Cause, levels = cuz)) %>% 
  select(Cause, Subgroup, Value, HR, HR.L, HR.U, pU, pS, pR)

save(out.urbanicity, file = here('output','analysis','out-urbanicity.RDa'))

rm(out.urban.t, out.suburban.t, out.rural.t, out.urbanicity.t,
   loc.urban, loc.suburban, loc.rural)
```

```{r Output SES Urban}
out.sesL.t = data.frame()
for (i in 1:4){
  load(here('output','analysis', 'New folder', paste('out-sesL-',i,'.RDa', sep= "")))
  out.sesL.t  <-  rbind(out.sesL.t, ses.Low) %>% 
    filter(!is.na(Outcome))
  }

out.sesM.t = data.frame()
for (i in 1:4){
  load(here('output','analysis', 'New folder', paste('out-sesM-',i,'.RDa', sep= "")))
  out.sesM.t  <-  rbind(out.sesM.t, ses.Mid) %>% 
    filter(!is.na(Outcome))
  }

out.sesH.t = data.frame()
for (i in 1:4){
  load(here('output','analysis','New folder',paste('out-sesH-',i,'.RDa', sep= "")))
  out.sesH.t  <-  rbind(out.sesH.t, ses.High) %>% 
    filter(!is.na(Outcome))
  }

out.sesUrban.t <- out.sesL.t %>% 
  add_row(out.sesM.t) %>% 
  add_row(out.sesH.t)
  
out.sesUrban <- out.sesUrban.t %>% 
  merge(Outcome.to.Cause) %>% 
  mutate(Coef = as.numeric(as.character(O3_B)),
         std = as.numeric(as.character(O3_SE)),
         HR = round(exp(Coef * 10/1000),3),
         HR.L = round(exp((Coef-1.96*std) * 10/1000),3),
         HR.U = round(exp((Coef+1.96*std) * 10/1000),3),
         Subgroup = "Income Urban", 
         Value = case_when(SES_cat == "Mid" ~ "Middle",
                           T ~ as.character(SES_cat)),
         Value = factor(Value, levels = c("High", "Middle", "Low")),
         Cause = factor(Cause, levels = cuz)) %>% 
  select(Cause, Subgroup, Value, HR, HR.L, HR.U, pL, pM, pH)

save(out.sesUrban, file = here('output','analysis','out-sesUrban.RDa'))

rm(out.sesL.t, out.sesM.t, out.sesH.t, out.sesUrban.t,
   ses.Low, ses.Mid, ses.High)
```

```{r Output Region}
out.W.t = data.frame()
for (i in 1:4){
  load(here('output','analysis','New folder',paste('out-west-',i,'.RDa', sep= "")))
  out.W.t  <-  rbind(out.W.t, region.W) %>% 
    filter(!is.na(Outcome))
  }

out.MW.t = data.frame()
for (i in 1:4){
  load(here('output','analysis','New folder',paste('out-midwest-',i,'.RDa', sep= "")))
  out.MW.t  <-  rbind(out.MW.t, region.MW) %>% 
    filter(!is.na(Outcome))
  }

out.S.t = data.frame()
for (i in 1:4){
  load(here('output','analysis','New folder',paste('out-south-',i,'.RDa', sep= "")))
  out.S.t  <-  rbind(out.S.t, region.S) %>% 
    filter(!is.na(Outcome))
  }

out.NE.t = data.frame()
for (i in 1:4){
  load(here('output','analysis','New folder', paste('out-northeast-',i,'.RDa', sep= "")))
  out.NE.t  <-  rbind(out.NE.t, region.NE) %>% 
    filter(!is.na(Outcome))
  }

out.region.t <- out.W.t %>% 
  add_row(out.MW.t) %>% 
  add_row(out.S.t) %>% 
  add_row(out.NE.t)
  
out.region <- out.region.t %>% 
  merge(Outcome.to.Cause) %>% 
  mutate(Coef = as.numeric(as.character(O3_B)),
         std = as.numeric(as.character(O3_SE)),
         HR = round(exp(Coef * 10/1000),3),
         HR.L = round(exp((Coef-1.96*std) * 10/1000),3),
         HR.U = round(exp((Coef+1.96*std) * 10/1000),3),
         Subgroup = "Region", 
         Value = factor(region_Cat, levels = c("NE", "S", "MW", "W")),
         Cause = factor(Cause, levels = cuz)) %>% 
  select(Cause, Subgroup, Value, HR, HR.L, HR.U, pW, pMW, pS, pNE)

save(out.region, file = here('output','analysis','out-region.RDa'))

rm(out.W.t, out.MW.t, out.S.t, out.NE.t, out.region.t, 
   region.W, region.MW, region.S, region.NE)
```

```{r Output Bufferzone}
out.bz6.t = data.frame()
for (i in 1:4){
  load(here('output','analysis','New folder',paste('out-pm-',i,'.RDa', sep= "")))
  out.bz6.t  <-  rbind(out.bz6.t, out.pm) %>% drop_na()
  }
out.bz6.t <- out.bz6.t %>% 
    mutate(Value = "6-mile")

out.bz12.t = data.frame()
for (i in 1:4){
  load(here('output','analysis','New folder',paste('out-pm-bz12-',i,'.RDa', sep= "")))
  out.bz12.t  <-  rbind(out.bz12.t, out.pm.bz12) %>% drop_na()
  }
out.bz12.t <- out.bz12.t %>% 
    mutate(Value = "12-mile")

out.bz24.t = data.frame()
for (i in 1:4){
  load(here('output','analysis','New folder',paste('out-pm-bz24-',i,'.RDa', sep= "")))
  out.bz24.t  <-  rbind(out.bz24.t, out.pm.bz24) %>% drop_na()
  }
out.bz24.t <- out.bz24.t %>% 
    mutate(Value = "24-mile")

out.buffer.t <- out.bz6.t %>% 
  add_row(out.bz12.t) %>% 
  add_row(out.bz24.t)
  
out.buffer <- out.buffer.t %>% 
  merge(Outcome.to.Cause) %>% 
  mutate(Coef = as.numeric(as.character(O3_B)),
         std = as.numeric(as.character(O3_SE)),
         HR = round(exp(Coef * 10/1000),3),
         HR.L = round(exp((Coef-1.96*std) * 10/1000),3),
         HR.U = round(exp((Coef+1.96*std) * 10/1000),3),
         Subgroup = "Buffer Zone",
         Value = factor(Value, levels = c("24-mile", "12-mile", "6-mile")),
         Cause = factor(Cause, levels = cuz)) %>% 
  select(Cause, Subgroup, Value, HR, HR.L, HR.U)

save(out.buffer, file = here('output','analysis','out-buffer.RDa'))

rm(out.bz6.t, out.bz12.t, out.bz24.t, out.buffer.t, 
   out.pm, out.pm.bz12, out.pm.bz24)
```

```{r Output Exposure Measure}
out.ses.maxh.t = data.frame()
for (i in 1:4){
  load(here('output','analysis','New folder',paste('out-ses-',i,'.RDa', sep= "")))
  out.ses.maxh.t  <-  rbind(out.ses.maxh.t, out.ses) %>% drop_na()
}
out.ses.maxh.t <- out.ses.maxh.t %>% 
    mutate(Value = "1-hr Max")

out.ses.8hmax.t = data.frame()
for (i in 1:4){
  load(here('output','analysis','New folder',paste('out-ses-8hmax-',i,'.RDa', sep= "")))
  out.ses.8hmax.t  <-  rbind(out.ses.8hmax.t, out.ses.8h) %>% drop_na()
}
out.ses.8hmax.t <- out.ses.8hmax.t %>% 
    mutate(Value = "8-hr Max")

out.ses.avgh.t = data.frame()
for (i in 1:4){
  load(here('output','analysis','New folder',paste('out-ses-avgh-',i,'.RDa', sep= "")))
  out.ses.avgh.t  <-  rbind(out.ses.avgh.t, out.ses.h) %>% drop_na()
}
out.ses.avgh.t <- out.ses.avgh.t %>% 
    mutate(Value = "24-hr Average")

out.ses.exp.t <- out.ses.maxh.t %>% 
  add_row(out.ses.8hmax.t) %>% 
  add_row(out.ses.avgh.t)
  
out.ses.exp <- out.ses.exp.t %>% 
  merge(Outcome.to.Cause) %>% 
  mutate(Coef = as.numeric(as.character(O3_B)),
         std = as.numeric(as.character(O3_SE)),
         HR = round(exp(Coef * 10/1000),3),
         HR.L = round(exp((Coef-1.96*std) * 10/1000),3),
         HR.U = round(exp((Coef+1.96*std) * 10/1000),3),
         Subgroup = "Base",
          Value = factor(Value, levels = c("24-hr Average", "8-hr Max", 
                                           "1-hr Max")),
         Cause = factor(Cause, levels = cuz)) %>% 
  select(Cause, Subgroup, Value, HR, HR.L, HR.U)

rm(out.ses.maxh.t, out.ses.8hmax.t, out.ses.avgh.t, out.ses.exp.t,
   out.ses, out.ses.8h, out.ses.h)
```

```{r Output Exposure Measure}
out.pm.maxh.t = data.frame()
for (i in 1:4){
  load(here('output','analysis','New folder',paste('out-pm-',i,'.RDa', sep= "")))
  out.pm.maxh.t  <-  rbind(out.pm.maxh.t, out.pm) %>% drop_na()
}
out.pm.maxh.t <- out.pm.maxh.t %>% 
    mutate(Value = "1-hr Max")

out.pm.8hmax.t = data.frame()
for (i in 1:4){
  load(here('output','analysis','New folder',paste('out-pm-8hmax-',i,'.RDa', sep= "")))
  out.pm.8hmax.t  <-  rbind(out.pm.8hmax.t, out.pm.8h) %>% drop_na()
}
out.pm.8hmax.t <- out.pm.8hmax.t %>% 
    mutate(Value = "8-hr Max")

out.pm.avgh.t = data.frame()
for (i in 1:4){
  load(here('output','analysis','New folder',paste('out-pm-avgh-',i,'.RDa', sep= "")))
  out.pm.avgh.t  <-  rbind(out.pm.avgh.t, out.pm.h) %>% drop_na()
}
out.pm.avgh.t <- out.pm.avgh.t %>% 
    mutate(Value = "24-hr Average")

out.pm.exp.t <- out.pm.maxh.t %>% 
  add_row(out.pm.8hmax.t) %>% 
  add_row(out.pm.avgh.t)
  
out.pm.exp <- out.pm.exp.t %>% 
  merge(Outcome.to.Cause) %>% 
  mutate(Coef = as.numeric(as.character(O3_B)),
         std = as.numeric(as.character(O3_SE)),
         HR = round(exp(Coef * 10/1000),3),
         HR.L = round(exp((Coef-1.96*std) * 10/1000),3),
         HR.U = round(exp((Coef+1.96*std) * 10/1000),3),
         Subgroup = "PM2.5-Adjusted",
         Value = factor(Value, levels = c("24-hr Average", "8-hr Max", 
                                          "1-hr Max")),
         Cause = factor(Cause, levels = cuz)) %>% 
  select(Cause, Subgroup, Value, HR, HR.L, HR.U)

rm(out.pm.maxh.t, out.pm.8hmax.t, out.pm.avgh.t, out.pm.exp.t,
   out.pm, out.pm.8h, out.pm.h)
```

```{r}
out.exposure <- out.ses.exp %>% 
  add_row(out.pm.exp) %>% 
  mutate(Subgroup = factor(Subgroup, levels = c("PM2.5-Adjusted", "Base")),
         Value = factor(Value, levels = c("24-hr Average", "8-hr Max", 
                                          "1-hr Max")),
         Cause = factor(Cause, levels = cuz))

save(out.exposure, file = here('output','analysis','out-exposure.RDa'))
```

```{r Output BRFSS}
out.brfss0.t = data.frame()
for (i in 1:4){
  load(here('output','analysis','New folder',paste('out-pm-brfss0-',i,'.RDa', sep= "")))
  out.brfss0.t  <-  rbind(out.brfss0.t, out.pm.brfss0) %>% drop_na()
}

out.brfss0.t <- out.brfss0.t %>% 
    mutate(Value = "Base")

out.brfss.t = data.frame()
for (i in 1:7){
  load(here('output','analysis','New folder',paste('out-pm-brfss-',i,'.RDa', sep= "")))
  out.brfss.t  <-  rbind(out.brfss.t, out.pm.brfss) %>% drop_na()
}

out.brfss.t <- out.brfss.t %>% 
    mutate(Value = "BRFSS-Adjusted")

out.brfss.t <- out.brfss0.t %>% 
  add_row(out.brfss.t)
  
out.brfss <- out.brfss.t %>% 
  merge(Outcome.to.Cause) %>% 
  mutate(Coef = as.numeric(as.character(O3_B)),
         std = as.numeric(as.character(O3_SE)),
         HR = round(exp(Coef * 10/1000),3),
         HR.L = round(exp((Coef-1.96*std) * 10/1000),3),
         HR.U = round(exp((Coef+1.96*std) * 10/1000),3),
         Subgroup = "BRFSS",
         Value = factor(Value, levels = c("BRFSS-Adjusted", "Base")),
         Cause = factor(Cause, levels = cuz)) %>% 
  select(Cause, Subgroup, Value, HR, HR.L, HR.U) %>% 
  filter(!str_detect(Cause, "Accid"))

save(out.brfss, file = here('output','analysis','out-brfss.RDa'))

rm(out.brfss0.t, out.brfss.t, out.pm.brfss0, out.pm.brfss)
```
